// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3STGeqgBJDDPkckR3cQCTga86pVAUaQ',
    appId: '1:527527334332:web:6d701742a7579e82a99bb9',
    messagingSenderId: '527527334332',
    projectId: 'nike-app-6d328',
    authDomain: 'nike-app-6d328.firebaseapp.com',
    storageBucket: 'nike-app-6d328.firebasestorage.app',
    measurementId: 'G-VESWTPFQVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-HLqVX_-vq33MqbghzNGRyp2W147uOg',
    appId: '1:527527334332:android:dac63dd2f7166cfea99bb9',
    messagingSenderId: '527527334332',
    projectId: 'nike-app-6d328',
    storageBucket: 'nike-app-6d328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVa4rOM_JSaowayWsxPui4pCj5r6u054',
    appId: '1:527527334332:ios:b38ba33c0a8cbae1a99bb9',
    messagingSenderId: '527527334332',
    projectId: 'nike-app-6d328',
    storageBucket: 'nike-app-6d328.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVa4rOM_JSaowayWsxPui4pCj5r6u054',
    appId: '1:527527334332:ios:b38ba33c0a8cbae1a99bb9',
    messagingSenderId: '527527334332',
    projectId: 'nike-app-6d328',
    storageBucket: 'nike-app-6d328.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3STGeqgBJDDPkckR3cQCTga86pVAUaQ',
    appId: '1:527527334332:web:998f1ab2f1b18ff9a99bb9',
    messagingSenderId: '527527334332',
    projectId: 'nike-app-6d328',
    authDomain: 'nike-app-6d328.firebaseapp.com',
    storageBucket: 'nike-app-6d328.firebasestorage.app',
    measurementId: 'G-Z5VKZE7K5B',
  );
}
