// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcvrVdt-SXw54JD4y78AEH8SK86ehhPQU',
    appId: '1:200040224684:web:1cdc3d2a6ffebabd358c09',
    messagingSenderId: '200040224684',
    projectId: 'meet-you-c0bfb',
    authDomain: 'meet-you-c0bfb.firebaseapp.com',
    storageBucket: 'meet-you-c0bfb.firebasestorage.app',
    measurementId: 'G-FRVDVJQS7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNqmC2KKRj2EEnlYd8LooMn5GoVkATWA',
    appId: '1:200040224684:android:1719c8889fa06888358c09',
    messagingSenderId: '200040224684',
    projectId: 'meet-you-c0bfb',
    storageBucket: 'meet-you-c0bfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhShVo60yk6AhR8egj7eHA8NMurAuCKlc',
    appId: '1:200040224684:ios:318b04e732f0e51e358c09',
    messagingSenderId: '200040224684',
    projectId: 'meet-you-c0bfb',
    storageBucket: 'meet-you-c0bfb.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhShVo60yk6AhR8egj7eHA8NMurAuCKlc',
    appId: '1:200040224684:ios:318b04e732f0e51e358c09',
    messagingSenderId: '200040224684',
    projectId: 'meet-you-c0bfb',
    storageBucket: 'meet-you-c0bfb.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcvrVdt-SXw54JD4y78AEH8SK86ehhPQU',
    appId: '1:200040224684:web:e6f2f9b2591b10e0358c09',
    messagingSenderId: '200040224684',
    projectId: 'meet-you-c0bfb',
    authDomain: 'meet-you-c0bfb.firebaseapp.com',
    storageBucket: 'meet-you-c0bfb.firebasestorage.app',
    measurementId: 'G-XTFZZGSTT0',
  );
}
